### ISSUE TITLE
Component linking not working - Storybook >= v6.4.0

### ISSUE THREAD

**Issue by ivankoop** [mertkahyaoglu/storybook-zeplin#41]
Hi,

I was trying to connect my storybook using version >= 6.4.0, and the following error was showing on the UI.

<img width="779" alt="Screen Shot 2021-12-17 at 10 36 17" src="https://user-images.githubusercontent.com/20506089/146553799-b7d8ceb8-f41d-48ad-8a00-7f18c325e97c.png">

Checking the storybook console using `storybook-zeplin/register` I can see an error.

```
vendors~main.manager.bundle.js:32094 Uncaught (in promise) TypeError: n is not a function
    at vendors~main.manager.bundle.js:32094
    at Generator.next (<anonymous>)
    at vendors~main.manager.bundle.js:32094
    at new Promise (<anonymous>)
    at n (vendors~main.manager.bundle.js:32094)
    at e (vendors~main.manager.bundle.js:32094)
    at vendors~main.manager.bundle.js:32094
    at Generator.next (<anonymous>)
    at a (vendors~main.manager.bundle.js:32094)
```

this error doesn't show using storybook < 6.4.
Component linking works using storybook < 6.4

Thanks.

**Comment by mertkahyaoglu** [comment]
@ivankoop Thanks for the issue. We'll look into this.

**Comment by ivankoop** [comment]
thanks guys!

Tested with `v1.6.1` and it's working 😄

**Comment by mertkahyaoglu** [comment]
Awesome 🎉  @ivankoop
